In [2]:
import pandas as pd
import numpy as np
import geopandas as gpd

# 1. Dengue

In [7]:
centro = pd.read_excel(r"datasets\dengue\lima_centro_2024.xlsx",sheet_name="Sheet1")
este = pd.read_excel(r"datasets\dengue\lima_este_2024.xlsx",sheet_name="Sheet1")
norte = pd.read_excel(r"datasets\dengue\lima_norte_2024.xlsx",sheet_name="Sheet1")
sur = pd.read_excel(r"datasets\dengue\lima_sur_2024.xlsx",sheet_name="Sheet1")
callao = pd.read_excel(r"datasets\dengue\callao_2024.xlsx",sheet_name="Sheet1")
base2024 = pd.concat([centro,este,norte,sur,callao],axis=0,ignore_index=True)

In [8]:
# Agregación de columna suma
base2024['Casos'] = base2024['Sin signos de alarma_total'] + base2024['Con signos de alarma_total'] + base2024['Grave_total']
base2024['Año'] = 2024
base2024 = base2024[['Año','Provincia','Distrito','Semana','Casos']]

In [9]:
base2023 = pd.read_csv(r'anexos\2023.csv').iloc[:,1:]
base2023

       Año Provincia                Distrito  Semana  Casos
0     2023      LIMA  SAN JUAN DE LURIGANCHO       1    1.0
1     2023      LIMA       SANTIAGO DE SURCO       1    1.0
2     2023      LIMA                     ATE       1    2.0
3     2023      LIMA              LURIGANCHO       1    2.0
4     2023      LIMA    SAN MARTIN DE PORRES       1    1.0
...    ...       ...                     ...     ...    ...
1020  2023    CALLAO                 MI PERU      52    3.0
1021  2023    CALLAO                  CALLAO      52    2.0
1022  2023    CALLAO              BELLAVISTA      52    0.0
1023  2023      LIMA    SAN MARTIN DE PORRES      52    1.0
1024  2023      LIMA              CHORRILLOS      52    1.0

[1025 rows x 5 columns]

In [9]:
detalle_distrito = gpd.read_file(r'datasets\distritos-peru@bogota-laburbano.geojson')
detalle_distrito

,geo_point_2d,ccdd,nombdep,ccpp,nombprov,ccdi,nombdist,capital,ubigeo,idprov,codigo,cnt_ccpp,descripcio,poblacion,fecha,dat_pob,geometry
0,"{'lon': -78.9176893007, 'lat': -7.36430408343}",06,CAJAMARCA,05,CONTUMAZA,04,GUZMANGO,GUZMANGO,060504,0605,060504,50,GUZMANGO,2864.0,2020.0,INEI,"POLYGON ((-78.91578 -7.32085, -78.91370 -7.322..."
1,"{'lon': -78.873085214, 'lat': -7.15904792997}",06,CAJAMARCA,12,SAN PABLO,03,SAN LUIS,SAN LUIS GRANDE,061203,0612,061203,9,SAN LUIS,949.0,2020.0,INEI,"POLYGON ((-78.87623 -7.09747, -78.87471 -7.098..."
2,"{'lon': -79.6713009573, 'lat': -7.01442466301}",14,LAMBAYEQUE,01,CHICLAYO,07,LAGUNAS,MOCUPE,140107,1401,140107,27,LAGUNAS,10899.0,2020.0,INEI,"POLYGON ((-79.66093 -6.90007, -79.65973 -6.900..."
3,"{'lon': -79.8574845687, 'lat': -6.86573035676}",14,LAMBAYEQUE,01,CHICLAYO,08,MONSEFU,MONSEFU,140108,1401,140108,44,MONSEFU,35368.0,2020.0,INEI,"POLYGON ((-79.78014 -6.82123, -79.77781 -6.821..."
4,"{'lon': -79.5066821013, 'lat': -6.8887009402}",14,LAMBAYEQUE,01,CHICLAYO,16,CAYALTI,CAYALTI,140116,1401,140116,18,CAYALTI,16364.0,2020.0,INEI,"POLYGON ((-79.44482 -6.82277, -79.44371 -6.823..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1870,"{'lon': -77.8605490277, 'lat': -5.52432929313}",01,AMAZONAS,03,BONGARA,12,YAMBRASBAMBA,YAMBRASBAMBA,010312,0103,010312,50,YAMBRASBAMBA,6013.0,2020.0,INEI,"POLYGON ((-77.74438 -5.13371, -77.73977 -5.136..."
1871,"{'lon': -78.523367636, 'lat': -6.01199768484}",01,AMAZONAS,07,UTCUBAMBA,07,YAMON,YAMON,010707,0107,010707,40,YAMON,3292.0,2020.0,INEI,"POLYGON ((-78.47479 -5.93642, -78.47356 -5.937..."
1872,"{'lon': -72.3768176137, 'lat': -15.4850465709}",04,AREQUIPA,04,CASTILLA,02,ANDAGUA,ANDAGUA,040402,0404,040402,16,ANDAGUA,1135.0,2020.0,INEI,"POLYGON ((-72.26159 -15.37631, -72.26098 -15.3..."
1873,"{'lon': -72.0687548294, 'lat': -15.4141378291}",04,AREQUIPA,04,CASTILLA,06,CHOCO,CHOCO,040406,0404,040406,58,CHOCO,812.0,2020.0,INEI,"POLYGON ((-71.96976 -15.13597, -71.96952 -15.1..."
1874,"{'lon': -76.9355515652, 'lat': -12.010572951}",15,LIMA,01,LIMA,44,SANTA MARIA DE HUACHIPA /1,SANTA MARIA,150144,1501,150144,1,SANTA MARIA,32826.0,2020.0,INEI,"POLYGON ((-76.90063 -12.01454, -76.90079 -12.0..."

In [23]:
clima = pd.read_csv('datasets/variables-climatológicas/metereologia.csv')
clima

,Fecha,Semana,Provincia,Distrito,Clima,Pluvio_Min,Pluvio_Max,Nubosidad,Presión,Viento_Min,Viento_Max,Temp_Min,Temp_Max,Punto_Rocío
0,2020-01-01,1,CALLAO,BELLAVISTA,Niebla,0.0,0.0,1.0,1012.0,4.0,13.0,19.0,22.0,19.0
1,2020-01-01,1,CALLAO,CALLAO,Niebla,0.0,0.0,1.0,1012.0,4.0,12.0,19.0,22.0,19.0
2,2020-01-01,1,CALLAO,CARMEN DE LA LEGUA REYNOSO,Niebla,0.0,0.0,0.7,1011.0,3.0,12.0,19.0,23.0,19.0
3,2020-01-01,1,CALLAO,LA PERLA,Niebla,0.0,0.0,1.0,1012.0,4.0,13.0,19.0,22.0,19.0
4,2020-01-01,1,CALLAO,LA PUNTA,Niebla,0.0,0.0,0.7,1012.0,5.0,13.0,19.0,22.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8245,2024-04-30,18,LIMA,SANTA ROSA,Despejado,0.0,0.0,0.3,1013.0,7.0,11.0,19.0,24.0,18.0
8246,2024-04-30,18,LIMA,SANTIAGO DE SURCO,Despejado,0.0,0.0,NaN,1011.0,6.0,15.0,19.0,24.0,17.0
8247,2024-04-30,18,LIMA,SURQUILLO,Despejado,0.0,0.0,NaN,1011.0,7.0,14.0,20.0,24.0,17.0
8248,2024-04-30,18,LIMA,VILLA EL SALVADOR,Despejado,0.0,0.0,0.3,1011.0,8.0,15.0,19.0,22.0,17.0
8249,2024-04-30,18,LIMA,VILLA MARIA DEL TRIUNFO,Despejado,0.0,0.0,0.2,1012.0,6.0,16.0,20.0,24.0,17.0

In [24]:
sql_dist = pd.merge(left=all_dists,right=detalle_distrito,how='left',left_on=['Provincia','Distrito'],right_on=['nombprov','nombdist'])
sql_dist = sql_dist[['ubigeo','Provincia','Distrito','Diris','poblacion','geo_point_2d','geometry']]
sql_dist.columns = ['Ubigeo','Provincia','Distrito','Diris','Población','Coordenadas','Polígono']
sql_dist.to_csv(r'datasets\sql_distritos.csv',index=False)

In [25]:
clima = pd.read_csv('datasets/variables-climatológicas/metereologia.csv')
sql_clima = pd.merge(left=clima,right=sql_dist,how='right',on=['Provincia','Distrito'])

sql_clima = sql_clima[['Fecha','Ubigeo','Semana'] + list(clima.columns[4:])]
sql_clima.to_csv(r'datasets\sql_clima.csv',index=False)

cómo el dinero puede ser utilizado para reparar los daños creados

In [12]:
all_dists = pd.read_csv(r'datasets\dengue\distritos_lima_callao.csv')[['Provincia','Distrito','Diris']]
all_dists

   Provincia                    Distrito   Diris
0       LIMA                       ANCON   NORTE
1       LIMA                         ATE    ESTE
2       LIMA                    BARRANCO     SUR
3     CALLAO                  BELLAVISTA  CALLAO
4       LIMA                       BREÑA  CENTRO
5     CALLAO                      CALLAO  CALLAO
6       LIMA                  CARABAYLLO   NORTE
7     CALLAO  CARMEN DE LA LEGUA REYNOSO  CALLAO
8       LIMA                  CHACLACAYO    ESTE
9       LIMA                  CHORRILLOS     SUR
10      LIMA                 CIENEGUILLA    ESTE
11      LIMA                       COMAS   NORTE
12      LIMA                 EL AGUSTINO    ESTE
13      LIMA               INDEPENDENCIA   NORTE
14      LIMA                 JESUS MARIA  CENTRO
15      LIMA                   LA MOLINA    ESTE
16    CALLAO                    LA PERLA  CALLAO
17    CALLAO                    LA PUNTA  CALLAO
18      LIMA                 LA VICTORIA  CENTRO
19      LIMA                        LIMA  CENTRO
20      LIMA                       LINCE  CENTRO
21      LIMA                  LOS OLIVOS   NORTE
22      LIMA                  LURIGANCHO    ESTE
23      LIMA                       LURIN     SUR
24      LIMA           MAGDALENA DEL MAR  CENTRO
25    CALLAO                     MI PERU  CALLAO
26      LIMA                  MIRAFLORES  CENTRO
27      LIMA                  PACHACAMAC     SUR
28      LIMA                    PUCUSANA     SUR
29      LIMA                PUEBLO LIBRE  CENTRO
30      LIMA               PUENTE PIEDRA   NORTE
31      LIMA               PUNTA HERMOSA     SUR
32      LIMA                 PUNTA NEGRA     SUR
33      LIMA                       RIMAC   NORTE
34      LIMA                 SAN BARTOLO     SUR
35      LIMA                   SAN BORJA  CENTRO
36      LIMA                  SAN ISIDRO  CENTRO
37      LIMA      SAN JUAN DE LURIGANCHO  CENTRO
38      LIMA      SAN JUAN DE MIRAFLORES     SUR
39      LIMA                    SAN LUIS  CENTRO
40      LIMA        SAN MARTIN DE PORRES   NORTE
41      LIMA                  SAN MIGUEL  CENTRO
42      LIMA                 SANTA ANITA    ESTE
43      LIMA         SANTA MARIA DEL MAR     SUR
44      LIMA                  SANTA ROSA   NORTE
45      LIMA           SANTIAGO DE SURCO     SUR
46      LIMA                   SURQUILLO  CENTRO
47    CALLAO                  VENTANILLA  CALLAO
48      LIMA           VILLA EL SALVADOR     SUR
49      LIMA     VILLA MARIA DEL TRIUNFO     SUR

In [6]:
base2024

      Año Provincia Distrito  Semana  Casos
0    2024      LIMA     LIMA       1      0
1    2024      LIMA     LIMA       2      0
2    2024      LIMA     LIMA       3      0
3    2024      LIMA     LIMA       4      0
4    2024      LIMA     LIMA       5      4
..    ...       ...      ...     ...    ...
156  2024    CALLAO  MI PERU      19     32
157  2024    CALLAO  MI PERU      20     13
158  2024    CALLAO  MI PERU      21      4
159  2024    CALLAO  MI PERU      22      6
160  2024    CALLAO  MI PERU      23      1

[1127 rows x 5 columns]

In [ ]:
decade = pd.read_csv('')

In [15]:
all_dists.shape

(50, 3)